# Generated by Django 5.0.1 on 2024-01-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstoreapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='no_of_authors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='books',
            name='no_of_books',
            field=models.IntegerField(default=0),
        ),
    ]
