# Generated by Django 5.0.1 on 2024-01-28 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstoreapp', '0002_authors_no_of_authors_books_no_of_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authors',
            name='no_of_authors',
        ),
        migrations.RemoveField(
            model_name='books',
            name='no_of_books',
        ),
    ]
