# Generated by Django 5.0.1 on 2024-01-28 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstoreapp', '0003_remove_authors_no_of_authors_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='author_name',
            new_name='author_id',
        ),
    ]
